from .main import main_bp
from .auth import auth_bp
from .products import products_bp
from .warehouses import warehouses_bp
from .stock import stock_bp
from .orders import orders_bp
from .reports import reports_bp
from .suppliers import suppliers_bp
from .customers import customers_bp